// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include "arduino_secrets.h"

const char SSID[]     = SECRET_WIFI_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_WIFI_PASS;    // Network password (use for WPA, or use as key for WEP)

void onLedExternalChange();
void onLedInternalChange();
void onModeChange();

bool button_led;
bool led_external;
bool led_internal;
bool mode;

void initProperties(){

  ArduinoCloud.addProperty(button_led, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(led_external, READWRITE, ON_CHANGE, onLedExternalChange);
  ArduinoCloud.addProperty(led_internal, READWRITE, ON_CHANGE, onLedInternalChange);
  ArduinoCloud.addProperty(mode, READWRITE, ON_CHANGE, onModeChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
