// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include "arduino_secrets.h"

const char SSID[]     = SECRET_WIFI_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_WIFI_PASS;    // Network password (use for WPA, or use as key for WEP)

void onLedChange();

int potentiometer;
int seconds;
bool led;

void initProperties(){

  ArduinoCloud.addProperty(potentiometer, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(seconds, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(led, READWRITE, ON_CHANGE, onLedChange);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);

